### PR TITLE
Add examples to Cargo

### LINKED ISSUE #48: Examples are not built in the build tests
Right now the CI just tests that the code compiles. This is useful to make sure if you're working on macOS, you haven't broken Linux or vice-versa.

However, if you are making API changes (generally changes to `lib.rs`) the tests will pass even though the examples may now fail to build.

I'm working on a fix for this, so if possible, this can be assigned to me.

### PR DESCRIPTION
**Pull request by obelisk**
This does a few things:

* Fixes having to manually change dependencies in ctapcli
* Adds all examples in the examples folder as cargo examples so they can be easily built
* Makes the new build tests build all examples so we can verify future PRs aren't breaking them

Closes #48

### CODE REVIEW

**Comment by gebogebogebo** [comment]
I will check this (#49) before #46.
It will take a few days to confirm.
Could you kindly wait for a couple of days?.
😺😺😺

**Comment by obelisk** [comment]
Of course, if you’re ok with this design (methods instead of functions) I
can move the rest of the code in the meantime.

If you’d like to think about it more thought I can wait.

Personally I think this design is better because it pairs the functions
that operate on the type WITH the type :)

Happy to have a discussion about it though!

**Comment by gebogebogebo** [comment]
question.

I am using vscode to run debugging.
I had configured [launch.json](https://github.com/gebogebogebo/ctap-hid-fido2/blob/master/examples/get-info/.vscode/launch.json) to run debugging get-info in vscode.

How should I configure launch.json to continue to debug get-info with vscode?.

**Comment by obelisk** [comment]
I'm not sure as I don't use VSCode for debugging but the binaries will now be `target/debug/examples` so I imagine setting up a similar launch.json points to the binary there should work :)

**Comment by gebogebogebo** [comment]
We found that we are no longer able to debug with vscode in this PR environment.

I cannot debug after creating the following configurations.

get-info/.vscode/launchi.json
```
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "lldb",
      "request": "launch",
      "name": "Rust Debug Launch",
      "program": "${workspaceRoot}/target/debug/${workspaceRootFolderName}",
      "args": [],
      "cwd": "${workspaceRoot}/target/debug/",
    }
  ]
}
```

Breakpoints and watches are not available.
This is a serious problem.
Could you please confirm this issue?

**Comment by obelisk** [comment]
I am not well versed in VSCode but I can look into this. The refactor of the code is completely separate from this so while I try to find a solution to this, I think we can focus on #46 :)

Will update you if I find out how to do it!

**Comment by obelisk** [comment]
I've fixed VSCode debugging. You should now see every example listed under the debug target and be able to work with them that way.

@gebogebogebo

**Comment by gebogebogebo** [comment]
@obelisk 
Awesome !
Thank you !

**Comment by gebogebogebo** [comment]
You are Superman !

**Comment by obelisk** [comment]
Happy to help!

**Pull request merged**
