### PR TITLE
Linux support

### PR DESCRIPTION
**Pull request by obelisk**
This improves Linux support in the repository by removing a lot of the linux specific code and instead relying on the crossplatform nature of `hidapi`. We use the libudev backend which does effectively what we were doing before, but since it happens in the dependency, we don't have to have conditional logic.

This means we can remove the entire fidokey_pi module and not worry about keeping it synchronized with fidopi.

It also means there is just less code to maintain and have to write separate tests for.

### CODE REVIEW

**Comment by obelisk** [comment]
Tests are running here on by fork: https://github.com/obelisk/ctap-hid-fido2/pull/2

**Comment by obelisk** [comment]
Let me rebase this on develop so the tests run :)

**Comment by obelisk** [comment]
I think approval needs to be granted (since I am not a maintainer of this repository) but should be good now :)

**Comment by gebogebogebo** [comment]
question.

On my environment I got a build error.
- Raspberry Pi OS 32bit
- libusb-1.0-0-dev installed

Build succeeded after installing libudev-dev package.
```
sudo apt-get install libudev-dev
```

Does normal Linux have libudev-dev installed by default?
Or do I need to install it like this?

**Comment by obelisk** [comment]
No, this adds a new C dependency of libudev to handle the hidraw. You can see in the linux tests that I install both libusb and libudev.

**Comment by obelisk** [comment]
Also, if we merge #49 first. I can rebase this on that and then we'll get to see all the example get tested with this rewrite on both macOS and Linux

**Comment by gebogebogebo** [comment]
Thanks.
I had missed it mentioned here as well.
https://github.com/gebogebogebo/ctap-hid-fido2/blob/master/.github/workflows/rust.yml#L27

**Comment by gebogebogebo** [comment]
Very Nice
You are great !!!

**Pull request merged**
